DisplayCard/force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Department Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DisplayCard/force-app/main/default/objects/Department__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <label>Department Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cars/Cars/force-app/main/default/objects/Expense_Item__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Cab Fare</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Air Fare</fullName>
            </value>
            <value>
                <fullName>Bus Fare</fullName>
            </value>
            <value>
                <fullName>Train Fare</fullName>
            </value>
            <value>
                <fullName>Per Diem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DisplayCard/force-app/main/default/objects/Expense_Item__c/fields/Travel_Request__c.field-meta.xml
<CustomField>
    <fullName>Travel_Request__c</fullName>
    <label>Travel Request</label>
    <referenceTo>Travel_Request__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/Travel_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Travel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Travel Requests</relationshipLabel>
    <relationshipName>Travel_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Out_of_State__c.field-meta.xml
<CustomField>
    <fullName>Out_of_State__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of State</label>
    <type>Checkbox</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Place_of_Travel__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Travel__c</fullName>
    <label>Place of Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Dehradun</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Mangalore</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Andaman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Request_Name__c</fullName>
    <label>Request Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Travel_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Draft</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Under Approval Consideration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <label>Total Expense</label>
    <summarizedField>Expense_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Expense_Item__c.Travel_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Cars/Cars/force-app/main/default/classes/TravelRequestDetailController.cls
public class TravelRequestDetailController {
    public List<Travel_Request__c> travelReqDetail{get;set;}
    public List<Expense_Item__c> expenseItemLst{get;set;}
    public TravelRequestDetailController(){
         Id traReqId = System.currentPageReference().getParameters().get('travelReqId');
        travelReqDetail = [SELECT Id,Name,Department__r.Department_Name__c,Place_of_Travel__c,Out_of_State__c,Request_Name__c,
                           Start_Date__c,End_Date__c,Status__c,Total_Expense__c FROM Travel_Request__c
                           WHERE Id=:traReqId ];
        expenseItemLst = [SELECT Id,Name,Amount__c,Expense_Type__c from Expense_Item__c	WHERE Travel_Request__c=:traReqId];
    }
    public PageReference goback(){
        PageReference pr = new PageReference('/apex/TravelRequestPage');
        pr.setRedirect(true);
        return pr;
    }
}