DisplayCard/force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Department Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DisplayCard/force-app/main/default/objects/Department__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <label>Department Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/Travel_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Travel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Travel Requests</relationshipLabel>
    <relationshipName>Travel_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Out_of_State__c.field-meta.xml
<CustomField>
    <fullName>Out_of_State__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of State</label>
    <type>Checkbox</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Place_of_Travel__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Travel__c</fullName>
    <label>Place of Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Dehradun</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Mangalore</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Andaman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Request_Name__c</fullName>
    <label>Request Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Travel_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Draft</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Under Approval Consideration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <label>Total Expense</label>
    <summarizedField>Expense_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Expense_Item__c.Travel_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Cars/Cars/force-app/main/default/classes/TravelRequestcontroller.cls
public class TravelRequestcontroller {
    public List<Travel_Request__c> travelreqs{get;set;}
    public string TravelReqId{get;set;}
    Travel_Request__c tr= new Travel_Request__c();
    public List<Travel_Request__c> insertTravelReq{get;set;}
    public string searchString{get;set;}
    public string onKeySearchStr{get;set;}
    private integer counter=0;
    private integer list_size=5;
    public integer total_size;
    public TravelRequestcontroller(){
        insertTravelReq = new list<Travel_Request__c>();
        insertTravelReq.add(tr);
        travelreqs =[SELECT Id,Name,Department__r.Department_Name__c,Place_of_Travel__c,Out_of_State__c,
                     Request_Name__c,Start_Date__c,End_Date__c,Status__c,
                     Total_Expense__c 
                     FROM Travel_Request__c
                     limit:list_size
                     offset:counter
                    ];
        total_size =[SELECT count() FROM Travel_Request__c];
        System.debug('total_size'+total_size);
             System.debug('list_size'+list_size);
             System.debug('counter'+counter);
    } 
    public PageReference viewExpenses(){
       PageReference pg = new PageReference('/apex/TravelRequestDetail?travelReqId='+TravelReqId);
        pg.setRedirect(true);
        return pg; 
    }
    public PageReference createNewReq(){
        PageReference pref = new PageReference('/apex/CreateTravelRequest');
        pref.setRedirect(true);
        return pref;
    }
    public PageReference createExpenses(){
        PageReference pref1 = new PageReference('/apex/CreateTravelRequest?createExpense=true&trReqId='+TravelReqId);
        pref1.setRedirect(true);
        return pref1;
    }
    public void searchRequests(){
        string searchStr = 'SELECT Id,Name,Department__r.Department_Name__c,Place_of_Travel__c,Out_of_State__c,Request_Name__c,'+
                            'Start_Date__c,End_Date__c,Status__c,Total_Expense__c FROM Travel_Request__c '+
                           'WHERE Request_Name__c LIKE \'%'+searchString+'%\'';
        System.debug(searchStr);
     //   if((!isBlank(searchString))){
               travelreqs = Database.query(searchStr);
         
      //  }
    }
    public void clearSearch(){
      travelreqs  = [SELECT Id,Name,Department__r.Department_Name__c,Place_of_Travel__c,Out_of_State__c,Request_Name__c,Start_Date__c,End_Date__c,Status__c,Total_Expense__c FROM Travel_Request__c];  
    }
    public pagereference start(){
        counter=0;
        getRecords();
        return null;
    }
    public pagereference end(){
        counter= total_size-math.mod(total_size,list_size);
        return null;
    }
    public pagereference next(){
        counter = counter+list_size;
        getRecords();
        system.debug('inside next'+list_size);
        system.debug('counter'+counter);
        return null;
    }
    public pagereference prev(){
        counter = counter-list_size;
         getRecords();
        return null;
    }
    public void getRecords(){
         travelreqs =[SELECT Id,Name,Department__r.Department_Name__c,Place_of_Travel__c,Out_of_State__c,
                     Request_Name__c,Start_Date__c,End_Date__c,Status__c,
                     Total_Expense__c 
                     FROM Travel_Request__c
                     limit:list_size
                     offset:counter
                    ];
    }

}