DisplayCard/force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cars/Cars/force-app/main/default/objects/Expense_Item__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Cab Fare</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Air Fare</fullName>
            </value>
            <value>
                <fullName>Bus Fare</fullName>
            </value>
            <value>
                <fullName>Train Fare</fullName>
            </value>
            <value>
                <fullName>Per Diem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DisplayCard/force-app/main/default/objects/Expense_Item__c/fields/Travel_Request__c.field-meta.xml
<CustomField>
    <fullName>Travel_Request__c</fullName>
    <label>Travel Request</label>
    <referenceTo>Travel_Request__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/Travel_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Travel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Out_of_State__c.field-meta.xml
<CustomField>
    <fullName>Out_of_State__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of State</label>
    <type>Checkbox</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Place_of_Travel__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Travel__c</fullName>
    <label>Place of Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Dehradun</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Mangalore</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Andaman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/fields/Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Request_Name__c</fullName>
    <label>Request Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Travel_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Draft</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Under Approval Consideration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DisplayCard/force-app/main/default/classes/TravelRequestLWCController.cls
public with sharing class TravelRequestLWCController {

    public without sharing class travelRequestWrapper{
        @AuraEnabled public string travelRequestName{get;set;}
        @AuraEnabled public Id travelRequestId{get;set;}
        @AuraEnabled public string travelRequestNumber{get;set;}    
        @AuraEnabled public Date travelStartDate;
        @AuraEnabled public Date travelEndDate;
        @AuraEnabled public string travelStatus;
        @AuraEnabled public boolean OutofState;
        @AuraEnabled public string placeOfTravel;
        @AuraEnabled public List<expenseWrapper> expenses{get;set;}
    }
    public without sharing class expenseWrapper{
        @AuraEnabled public Id expenseId;
        @AuraEnabled public decimal expAmount;
        @AuraEnabled public string expenceNum;   
        @AuraEnabled public string expenseType;
    }
    @AuraEnabled(cacheable=true)
    public static List<travelRequestWrapper> getTravelRequests(){
        try {
            Map<Id,travelRequestWrapper> travelReqMap = new Map<Id,travelRequestWrapper>();
            Map<Id,List<expenseWrapper>> finalExpWrapper = new Map<Id,List<expenseWrapper>>();
            List<travelRequestWrapper> wrapper = new List<travelRequestWrapper>();
            travelRequestWrapper wr = new travelRequestWrapper();
            for(Travel_Request__c t:[SELECT Id,Name,Request_Name__c,End_Date__c,Start_Date__c,Status__c,Out_of_State__c,Place_of_Travel__c from Travel_Request__c]){
                wr = new travelRequestWrapper();
                wr.travelRequestId = t.Id;
                wr.travelRequestNumber = t.Name;
                wr.travelRequestName = t.Request_Name__c;
                wr.travelStartDate = t.Start_Date__c;
                wr.travelEndDate = t.End_Date__c;
                wr.travelStatus = t.Status__c;
                wr.OutofState = t.Out_of_State__c;
                wr.placeOfTravel = t.Place_of_Travel__c;
                wrapper.add(wr);
                travelReqMap.put(wr.travelRequestId,wr);
            }
           List<expenseWrapper> expWrapperLst = new List<expenseWrapper>();
           expenseWrapper exWrapper = new expenseWrapper();
            for(Expense_Item__c ex:[SELECT Id,Expense_Type__c,Name,Description__c,Amount__c,Travel_Request__c from Expense_Item__c
                                    WHERE Travel_Request__c IN:travelReqMap.keySet()]){
                                        exWrapper = new expenseWrapper();
                                        if(expWrapperLst == NULL){
                                            expWrapperLst = new List<expenseWrapper>();
                                        }
                                        exWrapper.expenseId = ex.Id;
                                        exWrapper.expAmount = ex.Amount__c;
                                        exWrapper.expenceNum = ex.Name;    
                                        exWrapper.expenseType = ex.Expense_Type__c;  
                                        expWrapperLst.add(exWrapper);  
                                        wr.expenses = expWrapperLst;
                                        travelReqMap.put(ex.Travel_Request__c,wr);
                                      //  finalExpWrapper.put(ex.Travel_Request__c,expWrapperLst);                        
            }
           /* for(Id travelReqId:travelReqMap.keySet()){
              wr = new travelRequestWrapper();
              wr =   travelReqMap.get(travelReqId);
              wr.expenses =finalExpWrapper.get(travelReqId);
              travelReqMap.put(travelReqId,wr);
            }*/

            System.debug('wrapper'+wrapper);
            return travelReqMap.values();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static void deleteTravelRequest(List<Id> travelReqIdLst){
        try {
            List<Travel_Request__c> travLst = new List<Travel_Request__c>();
            if(travelReqIdLst != null){
              for(Travel_Request__c tr:[SELECT Id from Travel_Request__c WHERE Id IN:travelReqIdLst]){
                travLst.add(tr);
              }
              if(travLst.size() > 0){
                  delete travLst;
              }
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static Id createTravelRequest(Travel_Request__c travelReq){
        try {
            Id travelReqId;
            if(travelReq != null){
                insert travelReq;
                travelReqId = travelReq.Id;
               
            }
            return travelReqId;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(Cacheable=true)
    public static Travel_Request__c getSpecificTravelReqDetails(Id travelRequestId){
            return [SELECT Id,Name,Request_Name__c,End_Date__c,Start_Date__c,Status__c,Out_of_State__c,Place_of_Travel__c from Travel_Request__c WHERE Id=:travelRequestId];           
    }
    @AuraEnabled
    public static void insertExpenses(List<Expense_Item__c> expenseLst, Id travelRequestId){
        try {
            system.debug('travelRequestId'+travelRequestId);
            List<Expense_Item__c> expLst = new List<Expense_Item__c>();
            if(expenseLst.size() > 0){
                for(Expense_Item__c exp:expenseLst){
                    Expense_Item__c ex = new Expense_Item__c();
                    ex.Amount__c = exp.Amount__c;
                    ex.Expense_Type__c = exp.Expense_Type__c;
                    ex.Travel_Request__c = exp.Travel_Request__c;
                    expLst.add(ex);
                }
                insert expLst;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}