DisplayCard/force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DisplayCard/force-app/main/default/objects/Expense_Item__c/fields/Travel_Request__c.field-meta.xml
<CustomField>
    <fullName>Travel_Request__c</fullName>
    <label>Travel Request</label>
    <referenceTo>Travel_Request__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Travel_Request__c/Travel_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Travel Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DisplayCard/force-app/main/default/classes/CreateTravelRequestController.cls
public class CreateTravelRequestController {
    public List<Travel_Request__c> travelReqLst{get;set;}
    public List<Expense_Item__c> expenseItemLst{get;set;}
    public Id travelRequestId{get;set;}
    public string createExpense{get;set;}
    Travel_Request__c tr = new Travel_Request__c();
    Expense_Item__c expItem = new Expense_Item__c();
    public CreateTravelRequestController(){
        createExpense = System.currentPageReference().getParameters().get('createExpense');
        travelRequestId = System.currentPageReference().getParameters().get('trReqId');
        travelReqLst = new List<Travel_Request__c>();
        travelReqLst.add(tr);
        expenseItemLst = new List<Expense_Item__c>();
        expenseItemLst.add(expItem);
    }
    public void saveTravelReq(){
        insert travelReqLst;
        for(Travel_Request__c t: travelReqLst)
        travelRequestId = t.Id;
    }
    public PageReference gobacktoHome(){
        PageReference pr = new PageReference('/apex/TravelRequestPage');
        pr.setRedirect(true);
        return pr;
        
    }
    public void saveExpenses(){
        for(Expense_Item__c e: expenseItemLst){
            e.Travel_Request__c = travelRequestId;
        }
        insert expenseItemLst;
    }
    public void addExpenses(){
        Expense_Item__c ex = new Expense_Item__c();
      expenseItemLst.add(ex);
    }
}