DisplayCard/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cars/Cars/force-app/main/default/objects/Reservation__c/fields/Registered_Course__c.field-meta.xml
<CustomField>
    <fullName>Registered_Course__c</fullName>
    <label>Registered Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Graphics</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cars/Cars/force-app/main/default/objects/Reservation__c/fields/Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>Registered_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Registered Date</label>
    <type>Date</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Reservation__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Student__c/fields/Roll_Number__c.field-meta.xml
<CustomField>
    <fullName>Roll_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Roll Number</label>
    <type>AutoNumber</type>
</CustomField>

DisplayCard/force-app/main/default/classes/DisplayStudentController.cls
public class DisplayStudentController {
    
    public class studentWrapperclass{
        @AuraEnabled
        public string studentName;
        @AuraEnabled
        public string studentEmail;
        @AuraEnabled
        public string studentNum;
        @AuraEnabled
        public string regNum;
        @AuraEnabled
        public string courseName;
        @AuraEnabled
        public date regDate;
        
        public studentWrapperclass(string studentName,string studentEmail,string studentNum,string regNum,string courseName,Date regDate){
            this.studentName = studentName;
            this.studentEmail = studentEmail;
            this.studentNum = studentNum;
            this.regNum= regNum;
            this.courseName = courseName;
            this.regDate = regDate;
        }
    }
    @AuraEnabled
    public static List<studentWrapperclass> getStudentDetails(){
        List<studentWrapperclass> newStudentWrap = new List<studentWrapperclass>();
        List<Student__c> studentWrap = new List<Student__c>();
        List<Reservation__c> regWrap = new List<Reservation__c>();
        studentWrap = [SELECT Id,Name,Email_Address__c,Date_of_Birth__c,Roll_Number__c,(SELECT Id,Name,Registered_Course__c,Registered_Date__c From Reservations__r)From Student__c];
        for(Student__c st: studentWrap){
            for(Reservation__c rc:st.Reservations__r){
                newStudentWrap.add(new studentWrapperclass(st.Name,st.Email_Address__c,st.Roll_Number__c,rc.Name, rc.Registered_Course__c,rc.Registered_Date__c));
            }
        }
        system.debug('newStudentWrap'+newStudentWrap);
        return newStudentWrap;
    }
}