Cars/Cars/force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cars/Cars/force-app/main/default/objects/Package__c/fields/Package_Items__c.field-meta.xml
<CustomField>
    <fullName>Package_Items__c</fullName>
    <label>Package Items</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
            <value>
                <fullName>Metal Items</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Fragile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DisplayCard/force-app/main/default/objects/Package__c/fields/Package_Pin__c.field-meta.xml
<CustomField>
    <fullName>Package_Pin__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <label>Package Pin</label>
    <type>AutoNumber</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Package__c/fields/Package_Weight__c.field-meta.xml
<CustomField>
    <fullName>Package_Weight__c</fullName>
    <label>Package Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Package__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Shipment__c/fields/Receiver_s_Phone__c.field-meta.xml
<CustomField>
    <fullName>Receiver_s_Phone__c</fullName>
    <label>Receiver&apos;s Phone</label>
    <type>Phone</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Shipment__c/fields/Sender_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_s_Name__c</fullName>
    <label>Sender&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Shipment__c/fields/Shipment_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Address__c</fullName>
    <label>Shipment Address</label>
    <type>TextArea</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Shipment__c/fields/Shipment_Pin__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Pin__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <externalId>true</externalId>
    <label>Shipment Pin</label>
    <type>AutoNumber</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Shipment__c/fields/Shipment_Receiver_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Receiver_s_Name__c</fullName>
    <label>Shipment Receiver&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Cars/Cars/force-app/main/default/objects/Shipment__c/fields/Shipper_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Phone_Number__c</fullName>
    <label>Shipper Phone Number</label>
    <type>Phone</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Not yet Dispatched</fullName>
            </value>
            <value>
                <fullName>Awaiting Courier Pickup</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cars/Cars/force-app/main/default/objects/Tracking_History__c/Tracking_History__c.object-meta.xml
<CustomObject>
    <label>Tracking History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Tracking History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cars/Cars/force-app/main/default/objects/Tracking_History__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Tracking_History__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Tracking Histories</relationshipLabel>
    <relationshipName>Tracking_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DisplayCard/force-app/main/default/objects/Tracking_History__c/fields/Source_Destination__c.field-meta.xml
<CustomField>
    <fullName>Source_Destination__c</fullName>
    <label>Source Destination</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Cars/Cars/force-app/main/default/classes/ShipmentAppController.cls
public class ShipmentAppController {

    public without sharing Class shipmentRequest{
        @AuraEnabled public Id shipmentId;
        @AuraEnabled public string shipmentName;
        @AuraEnabled public string senderName;
        @AuraEnabled public string shipmentAddress;
        @AuraEnabled public Date shipmentDate;
        @AuraEnabled public string shipmentPin;
        @AuraEnabled public string receiverName;  
        @AuraEnabled public string shipmentStatus;
        @AuraEnabled public List<packageDetails> packageList = new List<packageDetails>();
        @AuraEnabled public List<TrackingHistory> trackinghistoryList = new List<TrackingHistory>();
    }
    public without sharing Class packageDetails{
           @AuraEnabled public Id packageId;
        @AuraEnabled public string packagePin;
        @AuraEnabled public Decimal packageWt;
        @AuraEnabled public string packageItems;
    }
    public without sharing Class TrackingHistory{
           @AuraEnabled public Id trackingHistoryId;
        @AuraEnabled public string comments;
        @AuraEnabled public Date trackingDate;
        @AuraEnabled public string shipmentDestination;
        @AuraEnabled public string shipmentSource;
    }
    public without sharing Class responseWrapper{
        @AuraEnabled public List<shipmentRequest> shipmentRequests = new List<shipmentRequest>();
        @AuraEnabled public boolean success;
        @AuraEnabled public string message;
        public Object createResponse(Boolean success, string message,List<shipmentRequest> shipmentrequests){
            this.success = success;
            this.message = message;
            this.shipmentRequests = shipmentrequests;
            return this;
        } 
    }
    public static Object getShipmentRequests(){
        Object responseString;
        responseWrapper wrapper = new responseWrapper();
        try{
            //shipment details
           Map<Id, shipmentRequest> shipmentMap = new Map<Id,shipmentRequest>();
            shipmentRequest sh = new shipmentRequest();
            for(Shipment__c ship:[SELECT Id,Name,Receiver_s_Phone__c,Sender_s_Name__c,Shipment_Address__c,Shipment_Date__c,Shipment_Pin__c,
                                  Shipment_Receiver_s_Name__c,Shipper_Phone_Number__c,Status__c from Shipment__c]){
                                      sh = new shipmentRequest(); 
                                      sh.shipmentId = ship.Id;
                                      sh.shipmentName = ship.Name;
                                      sh.senderName = ship.Sender_s_Name__c;
                                      sh.shipmentAddress = ship.Shipment_Address__c;
                                      sh.shipmentDate = ship.Shipment_Date__c;
                                      sh.receiverName = ship.Shipment_Receiver_s_Name__c;
                                      sh.shipmentStatus = ship.Status__c;
                                      sh.shipmentPin = ship.Shipment_Pin__c;
                                      shipmentMap.put(ship.Id,sh);
                                          }
           // package details
            Map<Id,List<packageDetails>> packageMap = new Map<Id,List<packageDetails>>();
            List<packageDetails> packLst =  new List<packageDetails>();
            packageDetails pack = new packageDetails();
            for(Package__c pk : [SELECT Id,Package_Items__c,Package_Pin__c,Package_Weight__c from Package__c WHERE Shipment__c IN:shipmentMap.Keyset()])
            {
                pack = new packageDetails();
                packLst = packageMap.get(pk.Shipment__c);
                if(packLst == null){
                    packLst= new List<packageDetails>();
                }
                pack.packageId = pk.Id;
                pack.packagePin = pk.Package_Pin__c;
                pack.packageWt = pk.Package_Weight__c;
                pack.packageItems = pk.Package_Items__c;
                packLst.add(pack);
                packageMap.put(pk.Shipment__c,packLst);
            }
            for(Id shipmentId : shipmentMap.keyset()){
                
            }
         //tracking history
         Map<Id,List<TrackingHistory>> trackinghistoryMap = new Map<Id,List<TrackingHistory>>(); 
         List<TrackingHistory> trackingLst = new List<TrackingHistory>();
          TrackingHistory tHistory = new TrackingHistory();
            for(Tracking_History__c th:[SELECT Id from Tracking_History__c WHERE Shipment__c IN:shipmentMap.Keyset()]){
               tHistory = new   TrackingHistory();
               trackingLst = trackinghistoryMap.get(th.Shipment__c);
                if(trackingLst == NULL){
                   trackingLst = new List<TrackingHistory>();
                }
                tHistory.trackingHistoryId = th.Id;
                tHistory.comments = th.Comments__c;
                tHistory.trackingDate  = th.Date__c;
                tHistory.shipmentDestination = th.Destination__c;
                tHistory.shipmentSource = th.Source_Destination__c;
                trackingLst.add(tHistory);
                trackinghistoryMap.put(th.Shipment__c,trackingLst);
            }
            responseString = wrapper.createResponse(true, 'SUCCESS',shipmentMap.values());
        }catch(Exception e){
            throw(e);
        }
        return responseString;
    } 
}